baseURL: https://command-line-interface-pages.github.io/site.github.io
languageCode: en-us
title: Command Line Interface Pages
theme: terminal
enableEmoji: true
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  themeColor: pink
  fullWidthTheme: false
  centerTheme: true
  readingTime: true
  Toc: true
  TocTitle: Contents
  logo:
    logoText: "[C]ommand [L]ine [I]nterface [P]ages (CLIP)"
menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: 1
  - identifier: goals
    name: Goals
    url: /goals/
    weight: 2
  - identifier: future
    name: Future
    url: /future/
    weight: 3
  - identifier: guides
    name: Guides
    url: /guides/
    weight: 4
  - identifier: pr-guides
    name: Pull request guides
    url: /pr-guides/
    weight: 5
  - identifier: extensions
    name: Common extensions
    url: /extensions/
    weight: 6
  - identifier: editors
    name: Common editors
    url: /editors/
    weight: 7
  - identifier: projects
    name: Similar projects
    url: /projects/
    weight: 8
