baseURL: https://command-line-interface-pages.github.io/site.github.io
languageCode: en-us
title: Command Line Interface Pages
theme: terminal
enableEmoji: true
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  themeColor: blue
  fullWidthTheme: false
  centerTheme: true
  readingTime: true
  Toc: true
  TocTitle: Contents
  logo:
    logoText: "[C]ommand [L]ine [I]nterface [P]ages (CLIP)"
menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: 1
  - identifier: goals
    name: Goals
    url: /goals/
    weight: 1
  - identifier: future
    name: Future
    url: /future/
  - identifier: guides
    name: Guides
    url: /guides/
  - identifier: pr-guides
    name: Pull request guides
    url: /pr-guides/
  - identifier: projects
    name: Similar projects
    url: /projects/
