version: 3

tasks:
  default:
    deps: [lint-with-markdownlint, lint-with-jsonschema-cli]
  
  lint-with-markdownlint:
    cmds:
      - markdownlint **/*.md
  
  lint-with-jsonschema-cli:
    cmds:
      - |
        for file in data/*; do
          file=$(sed -E 's|.*/(.+)\.yaml|\1|' <<<"$file")
          env -C "data" jsonschema-cli validate "../schemas/$file.json" "$file.yaml"
        done
