name: Feature request
description: A feature request
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: Explain what the expected behavior should be
      value: |
        Ability to ...
  - type: textarea
    attributes:
      label: Possible implementation
      placeholder: Explain what can be done to implement the feature
